### ISSUE TITLE
Doesn't highlight as

### ISSUE THREAD

**Issue by mhmdanas** [dart-lang/dart-vim-plugin#101]
<img width="357" alt="Screen Shot 2020-03-17 at 11 06 37 PM" src="https://user-images.githubusercontent.com/32234660/76897003-f7870380-68a3-11ea-9150-a7905727f8af.png">

**Comment by cbracken** [comment]
@mhmdanas This is already supported -- see this line:
https://github.com/dart-lang/dart-vim-plugin/blob/c16efc107e8bccd927f71bc2815d48f3bf94f1b8/syntax/dart.vim#L27

Can you make sure:
1. that you're using the latest version
2. that your colour scheme makes the `Operator` highlight class obvious? Many don't.

**Comment by mhmdanas** [comment]
@cbracken you were right! Changing the color scheme showed that it worked correctly. Sorry for the inconvenience.

**Comment by cbracken** [comment]
No problem! Please file any issues you encounter!
