### ISSUE TITLE
File type not activated when loading dart files in Neovim

### ISSUE THREAD

**Issue by edyu** [dart-lang/dart-vim-plugin#106]
Using 0.4.3 on WSL. 
Plugin is added using Dein.
Somehow whenever I load a file with file extension .dart, the file type is not set to dart automatically. I have to manually do :set ft=dart in order for the plugin to work.

**Comment by edyu** [comment]
Looks like dart file type is not shipped with 0.4.3 for neovim.

**Comment by mukhtharcm** [comment]
@edyu is there any way to use this with neovim?
