### ISSUE TITLE
Auto format add semicolon?

### ISSUE THREAD

**Issue by npearson72** [dart-lang/dart-vim-plugin#112]
Is it possible for the auto formatting to automatically add the needed semi-colons? Currently the vim lsp tool I'm using only lints those problems. Would be nice if it just added them for me.

Or is this further upstream at the sdk?

**Comment by cbracken** [comment]
[dartfmt](https://github.com/dart-lang/dart_style/) itself is written such that it only ever makes changes to whitespace but never to the program AST it manipulates. I believe it now includes `--fix-*` flags that _may_ make changes to the code itself but I haven't given that a go so am unfamiliar with how those work.

Inserting missing semi-colons feels like a pretty tricky problem in general, but I'm sure there's a _subset_ of missing semi-colon scenarios the analyzer can catch pretty well. Overall, I don't think it'd be a fit for the vim plugin. But -- a few possibilities here:
* On the off chance that dartfmt has a `--fix` option that does this, I believe we already support custom flags for dartfmt (e.g. for number of columns), so you could add the flag there
* The analyzer has an API for quick fixes if I recall correctly, which is what's used in IDE support, if the analyzer already has a quick-fix for missing semicolon errors, it's possible that could be wired through via the LSP plugin 

The analyzer/linter includes support for quickfixes in its API, if I recall correctly. @natebosch would know if there's an easy way to wire those into vim. See the bit of the readme on [LSP plugins](https://github.com/dart-lang/dart-vim-plugin#how-do-i-configure-an-lsp-plugin-to-start-the-analysis-server).

**Comment by natebosch** [comment]
dartfmt does not have an option to insert semicolons. The analyzer does indeed have a quick fix for these. If you are using `vim-lsc` you can invoke it by hitting `ga` or `:LSClientFindCodeActions` while the cursor is on a line with a diagnostic about a missing semicolon, then tap the number corresponding to the fix. Other LSP clients likely have options for this, search for "code actions" in the docs for your client to get started.
