### ISSUE TITLE
Add documentation in README.md on improving overall Dart experience in Vim

### ISSUE THREAD

**Issue by cbracken** [dart-lang/dart-vim-plugin#18]
[This article](http://h-miyako.hatenablog.com/entry/2014/09/15/181753) (Japanese) provides details on fairly interactive setup.

One specific plugin probably worth calling out:
[vim-dartanalyzer](https://github.com/miyakogi/vim-dartanalyzer): a Dart-specific replacement for Syntastic.

**Comment by rbtnn** [comment]
https://github.com/dart-lang/dart-vim-plugin/pull/26
