### ISSUE TITLE
Unclosed square brackets in doc comments break highlighting

### ISSUE THREAD

**Issue by smanilov** [dart-lang/dart-vim-plugin#23]
Consider this example:

```
/// Print [.
printOpen() {
    print("[");
}

/// Print ].
printClose() {
    print("]");
}

int main() {
    printOpen();
    printClose();
}
```

Because the first `[` is not closed, all of the code until the next `]` is highlighted as a doc comment link. This usually breaks the highlighting for the code following the `]` too.

**Comment by rbtnn** [comment]
@smanilov hi. I fixed this. Please try this repository.

https://github.com/rbtnn/dart-vim-plugin/tree/fix_issue23

And I created a new isuue for this one.

https://github.com/dart-lang/dart-vim-plugin/pull/28
