### ISSUE TITLE
Nested comments are not recognized

### ISSUE THREAD

**Issue by joseluis** [dart-lang/dart-vim-plugin#29]
Dart has nested comments, but the vim highlighter doesn't recognize them. For example this code:

```dart
/*
/*
 Comment
 
 /* nested comment */
​
*/ // <-- not highlighted
​
main() {}
```

![nested-comments](https://cloud.githubusercontent.com/assets/5832068/13652068/7ea89e5e-e64a-11e5-93eb-8dde726c7706.png)

Related: https://github.com/dart-lang/sdk/issues/25931

**Comment by cbracken** [comment]
Fixed by #33.
