### ISSUE TITLE
:DartFmt loses unwritten changes

### ISSUE THREAD

**Issue by natebosch** [dart-lang/dart-vim-plugin#36]
The :DartFmt command works on the file on disk but doesn't write, or warn, if there are unwritten changes.

We should either write, warn and not format, or instead pipe the buffer content to stdin on dartfmt rather than operate on the disk version.

**Comment by cbracken** [comment]
I don't think we should perform a write unless the user asks us to. The ideal behaviour would be to format what's in the buffer *so long as* dartfmt terminates with exit code 0, otherwise display an error message.
