### ISSUE TITLE
Improve highlighting of long triple-quote strings

### ISSUE THREAD

**Issue by natebosch** [dart-lang/dart-vim-plugin#47]
With long triple-quote strings it's possible to confuse the highlighting because vim does not use the entire string as context.

One could use `:syntax sync fromstart` or `:syntax sync minlines=200` to as a workaround. Alternatively, could we do something with `syn-sync-grouphere` to make this unnecessary?

cc @sigmundch

**Comment by natebosch** [comment]
Hmm - should this already work: https://github.com/dart-lang/dart-vim-plugin/blob/b4114f250a4ccf83002b87a07dc813eb74d98bd9/syntax/dart.vim#L16

**Comment by sigmundch** [comment]
hmm, odd, I'll check again, maybe I'm imagining things...

**Comment by cbracken** [comment]
@natebosch do you have repro steps? I haven't seen this locally.

**Comment by natebosch** [comment]
I haven't been able to repro either - this came out of a conversation with @sigmundch 

I think we can close for now.
