### ISSUE TITLE
Add dart lang layer in spacevim

### ISSUE THREAD

**Issue by wsdjeg** [dart-lang/dart-vim-plugin#59]
Hi, I am author of [SpaceVim](https://github.com/SpaceVim/SpaceVim), and I want to add a `lang#dart` layer, I just read the code of current plugin, it provide many features, but still miss some features:

1. code completion
2. syntax lint on the fly
3. REPL
4. runner
5. debug

I want to implement these features, so does dart lang provide any command line tools for these features?

ref: https://github.com/SpaceVim/SpaceVim/issues/1206

**Comment by wsdjeg** [comment]
### runner

![2017-12-30-23 24 04](https://user-images.githubusercontent.com/13142418/34455403-1f6d4c3e-ed44-11e7-893f-09a6e64e27ed.png)

**Comment by natebosch** [comment]
>1. code completion
>2. syntax lint on the fly

Check out https://github.com/natebosch/dart_language_server. Also offers some refactoring support, jump to definition, find references, hover info.

>3. REPL

There is no official REPL. https://pub.dartlang.org/packages/dart_repl offers some support but I don't know how complete it is or whether it works with the latest SDK.

>4. runner

As you've discovered the Dart vm is the closest thing we have to a 'runner' - but not all Dart code will work in the vm. There is also code aimed at the web (via dart2js) or mobile (via flutter).

>5. debug

Code compiled to JS can be debugged like any other JS in the browser and Dart2JS supports sourcemaps. The VM has it's [own protocol](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md) and I don't know of any efforts to write an implementation for vim.

**Comment by wsdjeg** [comment]
greate， thank you!

**Comment by LinArcX** [comment]
Debug feature is awesome if it added to this plugin. other features can be achived with LSP.

**Comment by LinArcX** [comment]
I notice that there is a protocol for debugging called: _debug adapter protocol_(DAP) and for Dart, there is a vscode Plugin that implement it.
https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/
