### ISSUE TITLE
[dart-vim-plugin] cannot execute binary file: dartanalyzer

### ISSUE THREAD

**Issue by nathanmalishev** [dart-lang/dart-vim-plugin#61]
Hey,
I am probably missing something simple. After installation using vim-plug. I try to run the plugin commands in vim/neovim, but get the error `[dart-vim-plugin] cannot execute binary file: dartanalyzer`. I'm not sure how vim plugins work or where the binarys get installed to, to debug it more.
Any help in pointing me in the right direction would be great

**Comment by natebosch** [comment]
`dartanalyzer` should be installed with the SDK. What version of the SDK are you using? Does the command `dartanalyzer` work for you from a command line?

**Comment by nathanmalishev** [comment]
Correct, didn't install dart with the --content-shell flag !
