### ISSUE TITLE
Intellisense / auto completion

### ISSUE THREAD

**Issue by thepunkprogrammer** [dart-lang/dart-vim-plugin#62]
Can we have an ability to add auto  completion or intellisense in to vim ?

**Comment by sigmundch** [comment]
There is one already! :) 

We should document this better in the readme, but there is a pub-package and a vim plugin that work really nicely:

  * install dart_language_server (it's a pub package at https://github.com/natebosch/dart_language_server that wraps the Dart analyzer to comply with the LSC protocol)
  * install the [vim-lsc](https://github.com/natebosch/vim-lsc) that integrates it all together.

The plugin supports completion, jump-to-definition, find-references, highlight variables, and rename refactorings.
