### ISSUE TITLE
Auto close quickfix list after a successful format - if it was previously opened because of dartfmt

### ISSUE THREAD

**Issue by jonasreitemeyer** [dart-lang/dart-vim-plugin#67]
Hey,

im writing an app with flutter using your plugin and maybe its not your fault but i didnt find a solution.
The dartanalyzer binary is in my path, so it is called on every save by your plugin. If there are syntax errors a quickfix list is opened. But when i fix the errors and the analyzer runs through the code the quickfix list wont update itself. It still shows the previous error. 

I have two more points:
- Can you provide more settings? Like making the dartanalyzer run on :w optional?
- Is there a possibility to disable the quickfix list compelety? I dont need more than the line markers.

Greetings and keep up the great Work :)

**Comment by natebosch** [comment]
The behavior you are describing is not coming from this plugin. Perhaps you have another plugin installed which is doing this? Sounds like maybe ale?

This plugin does not analyze on every write and has no option to do so. It does have an option to format on write and that could open the quickfix list if there are syntax errors, but it wouldn't show general analysis errors. Format on write is optional and is defaulted to off.

We also don't use the sign column at all in this plugin so if you're seeing line markers they are coming from somewhere else and makes me think this probably isn't coming from dartfmt on write.

**Comment by natebosch** [comment]
There isn't any difference between calling `:DartFmt` and when it automatically formats on save.

> Additionally i can't close the quickfix list with :q as normal. This only opens the quickfix list in fullscreen and i can jump through the errors.

We definitely don't do anything that would make the window behave differently. We just use `cexpr` and [`copen`](https://github.com/dart-lang/dart-vim-plugin/blob/940addeedc7fd81cdc1d5765472c8f01a0d487d7/autoload/dart.vim#L13)
Nothing that would change the behavior of `:q` or cause it to be fullscreen.

You are likely still hitting some behavior of syntastic or some other plugin.

**Comment by jonasreitemeyer** [comment]
Im sorry for stealing your time. I disabled all but this plugin. Still the same behaviour and i only have this with .dart files. This is weird and maybe still comes from outside, but i have no idea. Thanks for your time

**Comment by jonasreitemeyer** [comment]
Thanks for the time, help and the plugin. :)

**Comment by jonahfang** [comment]
@jonasreitemeyer I have the same problem and fix it by change line 23 of file `dart-lang/dart-vim-plugin/autoload/dart.vim`:
```
    "if buffer_content ==# joined_lines[:-2] | return | endif
    if buffer_content ==# joined_lines[:-2]
       execute 'cclose'
       return
    endif
```
