### ISSUE TITLE
Improve syntax highlighting (types)

### ISSUE THREAD

**Issue by lleaff** [dart-lang/dart-vim-plugin#74]
Currently, there are no syntax rules to detect type annotations, other than a list of built-ins (`int`, `String`, etc).
It would be nice if any value used as a type could be highlighted, either in function arguments, return types, or variable declarations.

Here is a comparison screenshot, Vim with `dart-vim-plugin` on the left, VS Code with the Dart plugin on the right:
![image](https://user-images.githubusercontent.com/9746807/51616370-346a9b00-1f2a-11e9-87eb-947056116aa9.png)

For instance, in the line with: `Widget build(BuildContext context) {`,
_`Widget`_ and _`BuildContext`_ should be highlighted differently than _`context`_.

**Comment by cbracken** [comment]
Agreed that making assumptions about capital or underscore-capital identifiers feels a bit dodgy. 

Playing devil's advocate for a bit, it's worth noting that we already make certain assumptions about code being idiomatic -- e.g. we highlight `async` as a keyword, even when used as a local variable, which the spec (section 20.1.1) allows, since it's not a reserved word.

That said, I have no firm opinion one way or another.

**Comment by lleaff** [comment]
I agree that the long term solution is to have that provided by the language server as in VS Code. Tracking those issues in the major clients:
https://github.com/autozimu/LanguageClient-neovim/issues/383
https://github.com/prabirshrestha/vim-lsp/issues/198

The uppercase assumption seems like a smart temporary solution ! I played around a little bit with those rules:

```vim
syntax match   dartType           "\<[A-Z][A-Za-z0-9_]\+\>"
syntax match   dartConstant       "\<[A-Z][A-Z0-9_]\+\>"
```
Of course as you pointed out you then need to differentiate between `Type`, `Typedef` and `StorageClass` in your theme.

Personally I think it's a definite improvement, without it I find any language with C-style type annotations unreadable.

**Comment by changlizhi** [comment]
> Currently, there are no syntax rules to detect type annotations, other than a list of built-ins (`int`, `String`, etc).
> It would be nice if any value used as a type could be highlighted, either in function arguments, return types, or variable declarations.
> 
> Here is a comparison screenshot, Vim with `dart-vim-plugin` on the left, VS Code with the Dart plugin on the right:
> ![image](https://user-images.githubusercontent.com/9746807/51616370-346a9b00-1f2a-11e9-87eb-947056116aa9.png)
> 
> For instance, in the line with: `Widget build(BuildContext context) {`,
> _`Widget`_ and _`BuildContext`_ should be highlighted differently than _`context`_.

how are you,I'm a chinese engerineer,I see your picture you put here seems the plugin runs well.but it doesn't highlight my dartlang syntax.could you please paste your settings about dartlang in your .vimrc?I need your help, thanks!
