### ISSUE TITLE
Problem identing default flutter app

### ISSUE THREAD

**Issue by tiagofumo** [dart-lang/dart-vim-plugin#76]
Hi,

I use vim for most of my programming, so I would like to use it with flutter/dart projects as well. But when I try to indent any code (like the default main.dart file created with a flutter app) the indent gets all broken. I think the main problem is indenting after opening parenthesis, like in the print below

```dart
class ListApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
            primarySwatch: Colors.blue,
        ),
        home: Material(
            child: ListView(
                children: <Widget>[
                  ListTile(
                      leading: Icon(Icons.map),
                      title: Text('Map'),
                  ),
                  ListTile(
                      leading: Icon(Icons.photo_album),
                      title: Text('Album'),
                  ),
                  ListTile(
                      leading: Icon(Icons.phone),
                      title: Text('Phone'),
                  ),
                ],
            ),
        ),
        );
  }
}

```

So it is using 4 spaces after open parenthesis, even thought it is correctly using 2 spaces after open brackets. Also it is not indenting the `);` near the end there.

I tried applying these changes to the DartIndent() method on indent/dart.vim, but it creates other bugs
```vim
function! DartIndent()
  " Default to cindent in most cases
  let indentTo = cindent(v:lnum)

  let previousLine = getline(prevnonblank(v:lnum - 1))
  let currentLine = getline(v:lnum)

  " Don't indent after an annotation
  if previousLine =~# '^\s*@.*$'
    let indentTo = indent(v:lnum - 1)
  endif

  " Don't indent after a comment
  if previousLine =~# '^\s*//.*$'
    let indentTo = indent(v:lnum - 1)
  endif

  " trying to fix the ); indent
  if currentLine =~# '^\s*);$'
    let indentTo = indent(v:lnum - 1) - &shiftwidth
  endif

  " Indent after opening List literal
  if previousLine =~# '\[$' && !(currentLine =~# '^\s*\]')
    let indentTo = indent(v:lnum - 1) + &shiftwidth
  endif

  " Ident after opening parenthesis
  if previousLine =~# '($' && !(currentLine =~# '^\s*)')
    let indentTo = indent(v:lnum - 1) + &shiftwidth
  endif

  return indentTo
endfunction
```

And it worked on the previous code snippet, but it results in other errors, like these:

```dart
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

// This class is the configuration for the state. It holds the values (in this
// case the title) provided by the parent (in this case the App widget) and
// used by the build method of the State. Fields in a Widget subclass are
// always marked "final".

final String title;

@override
_MyHomePageState createState() => _MyHomePageState();
}

```

**Comment by natebosch** [comment]
Using 4 spaces after an opening paren _is_ correct behavior against `dartfmt` _except_ in one case which is when using a trailing comma with an argument list. We can't easily fix that without breaking behavior for all other cases (like argument lists without a trailing comma, asserts, long conditionals), especially considering that usually when editing that trailing comma doesn't exist yet.

I'll try to add a section about this to the README to make it more clear.

**Comment by cbracken** [comment]
@natebosch It's worth noting that Flutter's own SDK style doesn't use the 4-space continuation indents, preferring 2-space indent in all cases. Admittedly this is inconsistent with `dartfmt`. I do find that reads better for Flutter code, which can be fairly deeply nested, but haven't ever bothered to tweak my own settings to account for it. 

I could take a look. Seems like a reasonable option to offer.

**Comment by tiagofumo** [comment]
Just checking if I didn't misunderstand something, this indentation (made with dart-vim-plugin) is correct?
```dart
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
        appBar: AppBar(
            // Here we take the value from the MyHomePage object that was created by
            // the App.build method, and use it to set our appbar title.
            title: Text(widget.title),
        ),
        body: Center(
            // Center is a layout widget. It takes a single child and positions it
            // in the middle of the parent.
            child: Column(
                // Column is also layout widget. It takes a list of children and
                // arranges them vertically. By default, it sizes itself to fit its
                // children horizontally, and tries to be as tall as its parent.
                //
                // Invoke "debug painting" (press "p" in the console, choose the
                // "Toggle Debug Paint" action from the Flutter Inspector in Android
                // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
                // to see the wireframe for each widget.
                //
                // Column has various properties to control how it sizes itself and
                // how it positions its children. Here we use mainAxisAlignment to
                // center the children vertically; the main axis here is the vertical
                // axis because Columns are vertical (the cross axis would be
                // horizontal).
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Text(
                      'You have pushed the button this many times:',
                  ),
                  Text(
                      '$_counter',
                      style: Theme.of(context).textTheme.display1,
                  ),
                ],
                ),
                ),
                floatingActionButton: FloatingActionButton(
                    onPressed: _incrementCounter,
                    tooltip: 'Increment',
                    child: Icon(Icons.add),
                ), // This trailing comma makes auto-formatting nicer for build methods.
                );
  }
}

```

**Comment by natebosch** [comment]
> It's worth noting that Flutter's own SDK style doesn't use the 4-space continuation indents

Does the flutter SDK use 2 spaces for other stuff in parens? Like continuations for conditionals, or asserts? Do you always use 1 argument per line in function definitions and calls, or do you sometimes collapse for short argument lists?

If you want to make an option for switching to `)s` over `)2s` we could do that - but we should be explicit about our expectations around behavior, and I think we should optimize for `dartfmt` over the flutter SDK (those users can set custom `cinoptions` if they need 😝) . Dartfmt is still going to use `)2s` in _many_ cases that could feel just as jarring as it does today to see the function arguments move on format. I'd recommend trying it out for a bit to get the feel for it.

> Just checking if I didn't misunderstand something, this indentation (made with dart-vim-plugin) is correct?

It is not correct in that it doesn't match `dartfmt`, however it is "correct" in that I think it's the best we can do without re-implementing `dartfmt` in vim. We could let you change to `)s`, but as I mention above this might give behavior that you like worse since it won't match `dartfmt` in other ways.

If you want to try it and get a feel for what it would be like if we did give you an option you can add a file in your vim path like `after/ftplugin/dart.vim` and modify the `cinoptions`:

```viml
setlocal cinoptions-=(2s
setlocal cinoptions+=(s
```

**Comment by MonkeyInWind** [comment]
> I got these two small errors that look like can be fixed with a few lines, but if you tell me how to fix it, I will be ok:
> 
> I am testing possible fixes in the indent/dart.vim (I might create an after/ftplugin/dart.vim later or something, but for testing, it will do) and I a changed the cionptions line to this:
> 
> ```viml
> setlocal cinoptions+=(0,W2,J1,j1,m1,c0,C0,/0
> ```
> 
> It kinda worked, but 2 small problems still happen:
> https://pastebin.com/nVEYWh7D -> line 35 is not correctly indented
> https://pastebin.com/UXXrwPXQ -> same code as before but with comments, and now lines 56-64 are missing indentation

It's still a bit of a problem.
Before changed
![image](https://user-images.githubusercontent.com/34543887/51732109-28144880-20b8-11e9-8d09-a255c0b3cd97.png)

after I changed to 
`setlocal cinoptions+=(0,W2,J1,j1,m1,c0,C0,/0`

![image](https://user-images.githubusercontent.com/34543887/51732162-54c86000-20b8-11e9-9eb6-82d7661dff10.png)

I want to use 2 space too.

**Comment by natebosch** [comment]
There was also an attempt here: https://github.com/dart-lang/dart-vim-plugin/pull/73

I don't know what the usability was like with that combo.

**Comment by tiagofumo** [comment]
I see. Well, what you could do is add a global variable like 'g:dart_indent_2' or something and an if on indent/dart.vim like this:
```vim
setlocal cinoptions+=j1,J1,U1,m1,+2s
if exist(g:dart_indent_2)
  setlocal cinoptions+=(1s,u1s
else
  setlocal cinoptions+=(1s,u1s
endif

...

function! DartIndent()
...
  " do not indent );
  if currentLine =~# '^\s*);$'
    let indentTo = indent(v:lnum - 1) - &shiftwidth
  endif

  return indentTo
endfunction
```

This if in DartIndent before the return is to avoid indenting the ');', to avoid the error on https://pastebin.com/nVEYWh7D line 35

**Comment by tiagofumo** [comment]
I made [this](https://github.com/tiagofumo/dart-vim-flutter-layout), which solved my problems, and it's also handy for configuring multiple workstations.

**Comment by vyorkin** [comment]
@tiagofumo This indentation behavior perfectly matches my expectations. Do you think it makes sense to mention it in README of dart-vim-plugin or somewhere else? It is quite hard to find it otherwise :)
