### ISSUE TITLE
update readme to discuss configuring LSP support

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-vim-plugin#79]
The readme in this repo is pointed by by the VIM reference from https://www.dartlang.org/tools. We should update this to mention how to configure LSP support.

**Comment by natebosch** [comment]
Have we nailed down the command line to invoke the analysis server in LSP mode?

If we want our readme to stay agnostic towards particular plugins we could point out the options and give the command to start the server.

If we want our readme to be opinionated about using `vim-lsc` we could either add some logic in here to detect that it's being used and automatically configure the server, or put that into a separate plugin like `vim-lsc-dart`.

**Comment by devoncarew** [comment]
> Have we nailed down the command line to invoke the analysis server in LSP mode?

Yes, just `dart <snapshot path> --lsp`.

> If we want our readme to stay agnostic towards particular plugins we could point out the options and give the command to start the server.
> 
> If we want our readme to be opinionated about using `vim-lsc` we could either add some logic in here to detect that it's being used and automatically configure the server, or put that into a separate plugin like `vim-lsc-dart`.

Yeah, I don't have VIM plugins familiarity here, so suspect you're the best person to answer this :)

**Comment by natebosch** [comment]
> so suspect you're the best person to answer this :)

I'm also the most biased so I've been trying to avoid being too prescriptive 😉

**Comment by cbracken** [comment]
I'm probably as unbiased as it gets (I don't use code completion all, and I get my analysis on the command line using `flutter analyze --watch`) and I'm fully in favour of the readme mentioning LSP as I expect that's exactly what a sizeable subset of our users want.

**Comment by natebosch** [comment]
> I'm fully in favour of the readme mentioning LSP 

The question is whether we should be general and point out that there are multiple plugin options and users should go look up how to configure them, or whether we should pick vim-lsc as our recommended plugin and describe specifically how to configure it, or even do it automatically if we detect that the plugin is present.

**Comment by cbracken** [comment]
Right -- I think it's fine to recommend an end-to-end default solution in the readme file, but I'd definitely prefer that the code remain entirely opinion-free.

**Comment by mrmcq2u** [comment]
I'm interested in distributing dartsdk as flatpak extensions, the lsp support baked in will help a lot with dart support for ide's distributed using flatpak. e.g gnome-builder , visual studio code etc
