### ISSUE TITLE
Doesn't highlight Dart 2.7 extension keyword

### ISSUE THREAD

**Issue by mhmdanas** [dart-lang/dart-vim-plugin#99]
<img width="430" alt="Screen Shot 2020-03-07 at 2 47 29 PM" src="https://user-images.githubusercontent.com/32234660/76142845-93359a00-6082-11ea-9f6a-73a28c6d0557.png">

**Comment by cbracken** [comment]
Funny I ran into this the other day too, then promptly forgot to fix it. Give me 10 minutes and I'll have a patch out. Thanks for filing!

**Comment by cbracken** [comment]
This will be fixed by #100. 

![image](https://user-images.githubusercontent.com/351029/76150338-4770f980-605e-11ea-90b1-d167a1fe8b90.png)

**Comment by cbracken** [comment]
Fix has landed. Thanks again for reporting this!
